apiVersion: v1
kind: Service
metadata:
  name: calculator-microservice
spec:
  type: NodePort
  selector:
    app: calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 30080
